version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Clarusway_1
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - emin
  eminapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "9000:9000"
        networks:
            - emin

networks:
    emin:
        driver: bridge

